### ISSUE TITLE
cronet.dll

### ISSUE THREAD

**Issue by JonJSON** [sleeyax/CronetSharp#5]
13302566@qq.com

**Comment by sleeyax** [comment]
Please provide info about the issue. I can't use QQ and won't provide free private support anyways.

**Comment by sleeyax** [comment]
Closing as not enough info is provided. Create a new issue with clear title and description, maybe include an example as well.

**Comment by JonJSON** [comment]
Can you send the cronet.dll to my email

**Comment by sleeyax** [comment]
No, compile it yourself.
